import { GoogleGenAI } from "@google/genai";
import { json, z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("A score between 0 and 100 indicating how well the candidate matches the job description according to his selfdescription and resume."),
    technicalQuestion: z.array(z.object({
        question: z.string().describe("The technical question asked during the interview."),
        intension: z.string().describe("The intention behind asking the technical question."),
        answer: z.string().describe("The candidate's answer to the technical question."),})).describe("An array of technical questions asked during the interview, along with their intentions and the candidate's answers."),
    behavioralQuestion: z.array(z.object({
        question: z.string().describe("The behavioral question asked during the interview."),
        intension: z.string().describe("The intention behind asking the behavioral question."),     
        answer: z.string().describe("The candidate's answer to the behavioral question."),})).describe("An array of behavioral questions asked during the interview, along with their intentions and the candidate's answers."),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The specific skill that the candidate is lacking."),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap, categorized as low, medium, or high."),})).describe("An array of skill gaps identified during the interview, along with their severity levels."),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day of the preparation plan."),
        focus: z.number().describe("The focus area for the day."),
        tasks: z.array(z.string()).describe("The tasks to be completed on the day."),})).describe("An array of preparation steps for the interview."),
    title: z.string().describe("The title of the interview report."),
}).describe("The schema for the interview report generated by the AI, including match score, technical and behavioral questions, skill gaps, preparation plan, and title.");



async function generateInterviewReport({jobDescription, selfDescription, resume}) {

    const prompt = `You are an expert interviewer. Based on the following job description, self description and resume, create an interview report in the following format: ${JSON.stringify(zodToJsonSchema(interviewReportSchema))}. Job Description: ${jobDescription}, Self Description: ${selfDescription}, Resume: ${resume}`;
    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseJsonSchema: zodToJsonSchema(interviewReportSchema),
            },
    
        });
        return json.parse(response.text);
    } catch (error) {
        console.error("Error generating interview report:", error);
    }
}

export { generateInterviewReport };
