import { GoogleGenAI } from "@google/genai";
import { json, z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import puppeteer from "puppeteer";

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("A score between 0 and 100 indicating how well the candidate matches the job description according to his selfdescription and resume."),
    technicalQuestion: z.array(z.object({
        question: z.string().describe("The technical question asked during the interview."),
        intension: z.string().describe("The intention behind asking the technical question."),
        answer: z.string().describe("The candidate's answer to the technical question."),})).describe("An array of technical questions asked during the interview, along with their intentions and the candidate's answers."),
    behavioralQuestion: z.array(z.object({
        question: z.string().describe("The behavioral question asked during the interview."),
        intension: z.string().describe("The intention behind asking the behavioral question."),     
        answer: z.string().describe("The candidate's answer to the behavioral question."),})).describe("An array of behavioral questions asked during the interview, along with their intentions and the candidate's answers."),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The specific skill that the candidate is lacking."),
        severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap, categorized as low, medium, or high."),})).describe("An array of skill gaps identified during the interview, along with their severity levels."),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day of the preparation plan."),
        focus: z.number().describe("The focus area for the day."),
        tasks: z.array(z.string()).describe("The tasks to be completed on the day."),})).describe("An array of preparation steps for the interview."),
    title: z.string().describe("The title of the interview report."),
}).describe("The schema for the interview report generated by the AI, including match score, technical and behavioral questions, skill gaps, preparation plan, and title.");



async function generateInterviewReport({jobDescription, selfDescription, resume}) {

    const prompt = `You are an expert interviewer. Based on the following job description, self description and resume, create an interview report in the following format: ${JSON.stringify(zodToJsonSchema(interviewReportSchema))}. Job Description: ${jobDescription}, Self Description: ${selfDescription}, Resume: ${resume}`;
    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseJsonSchema: zodToJsonSchema(interviewReportSchema),
            },
    
        });
        return json.parse(response.text);
    } catch (error) {
        console.error("Error generating interview report:", error);
    }
}



const generatePdfFromHtml = async (htmlContent) => {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdfBuffer = await page.pdf({
        format: "A4", margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })
    await browser.close();
    return pdfBuffer;
}
    

const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
}).describe("The schema for the resume PDF generated by the AI, containing the HTML content of the resume.");
async function generateResumePdf({resume, selfDescription, jobDescription}) {
    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.`
    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseJsonSchema: zodToJsonSchema(resumePdfSchema),
            },
        });
        const jsonContent = json.parse(response.text);

        const pdfBuffer = await generatePdfFromHtml(jsonContent.html); // Implement this function to convert HTML to PDF using a library like puppeteer
        return pdfBuffer;
    } catch (error) {
        console.error("Error generating resume PDF:", error);
    }       
}



export { 
    generateInterviewReport, generateResumePdf 
}
